### ISSUE TITLE
SpringBoot中对JSP的部分研究

### ISSUE THREAD

**Issue by huayaoyue6** [huayaoyue6/blog#1]
Spring Boot的官方文档有下面的一段话：

When running a Spring Boot application that uses an embedded servlet container (and is packaged as an executable archive), there are some limitations in the JSP support.

> -  With Jetty and Tomcat, it should work if you use war packaging. An executable war will work when launched with java -jar, and will also be deployable to any standard container. JSPs are not supported when using an executable jar. 
> -  Undertow does not support JSPs. 
> -  Creating a custom error.jsp page does not override the default view for [error handling](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.error-handling). [Custom error pages](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.spring-mvc.error-handling.error-pages) should be used instead.

其中第一点说在如果想在Tomcat/Jetty的环境中正常运行JSP的话，可以通过打成war包，然后使用java -jar app.war的方式启动，或者部署到标准的servlet容器。打成jar包的方式是不支持jsp的。 

在[早期版本的文档](https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/html/boot-features-developing-web-applications.html)中还有下面的两句话：

> An executable jar will not work because of a hard coded file pattern in Tomcat.

> Do not use the src/main/webapp directory if your application will be packaged as a jar. Although this directory is a common standard, it will **only** work with war packaging and it will be silently ignored by most build tools if you generate a jar.

在老项目升级或上docker的时候，难免有很多jsp的项目。这个时候就遇见了jsp的问题。所以简单研究了一下。

简单介绍一下项目**A**和项目**C**。

项目**A为**原来的一个运行在docker中的项目，可以正确渲染出来JSP的项目。主要为SpringBoot2.x+**1.4.2**版本的plugin。配置的参考这个[链接](https://yanglukuan.github.io/2017/09/22/java/springboot/springboot/)或者这个[链接](https://juejin.cn/post/6844903785089728520#fromHistory)。

项目**C**是正在升级重构的老项目。准备从springmvc+tomcat部署的方式换成fat-jar的方式。项目**C**本地开发时jsp页面显示正常的，但是部署到docker中jsp页面就会报404。表现形式与上面给的链接中描述的一致。

理论上想正常运行jsp的话应该按照官方说的使用java -jar app.war的方式，按照链接中的解决方案中这种spring-boot 2.x配1.4.2版本的plugin应该是一种针对某种bug的利用的hack方式。

所以针对这个问题进行了简单的研究。过程中有下面的几个问题：

1. **为什么1.4.2版本的plugin可以运行**
2. **为什么非要配置到META-INF/resources目录才行**
3. **为什么本地IDE中运行是正常的**
4. **为什么使用java -jar app.war行而java -jar app.jar不行**

上面几个1和2是有一些关联的。下面一个一个分析。

## 第四个问题相关
首先先看第四个问题的原因：打成打jar包和war包目录结构不同。导致相关加载方式不同。下面为相关的资料。

先谈一下jar包的使用方式及规范。

在早期的时候，常见的使用方式为shaded方式。即将所有的类都打包到jar中。这种方式很难看到在应用程序中查看到实际使用的库。同时带来的问题容易出现不同版本的类的冲突。这种方式打的包在现在也能在一些类库中看见。

spring使用了一种新的打包方式，即我们说的fat-jar，将依赖的jar包直接以内嵌的方式打到最终的可运行的jar包中。同时遵循了下面说将的jar包的规范。

jar包的规范可以参考这个[链接](https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html)。其中重点是`META-INF`目录中的`MANIFEST.MF`文件。此文件中一个重要的属性为：`Main-Class`。下面为介绍：
> - attribute defined for stand-alone applications: This attribute is used by stand-alone applications that are bundled into executable jar files which can be invoked by the java runtime directly by running "java -jar x.jar".
>    - Main-Class: The value of this attribute is the class name of the main application class which the launcher will load at startup time. The value must _not_ have the .class extension appended to the class name.

说这个Main-Class属性用于“java -jar x.jar”命令启动的可执行jar包。定义的类会在启动的时候加载。

spring-boot-plugin打包的时候会生成可执行的jar包或者war包。下面为不同类型的格式的`Main-Class`的值：

- jar包：`Main-Class: org.springframework.boot.loader.JarLauncher`
- war包：`Main-Class: org.springframework.boot.loader.WarLauncher`

相关类的源码在spring-boot-loader包中，继承关系如下：
```java
org.springframework.boot.loader.Launcher
            	|
    ExecutableArchiveLauncher
    		|			
---------------------------------
|				|
JarLauncher		WarLauncher
```

在2.1.4.RELEASE版本中打出来的目录结构为：

- 可执行的jar包的目录结构：
```java
example.jar
 |
 +-META-INF
 |  +-MANIFEST.MF
 +-org
 |  +-springframework
 |     +-boot
 |        +-loader
 |           +-<spring boot loader classes>
 +-BOOT-INF
    +-classes
    |  +-mycompany
    |     +-project
    |        +-YourClasses.class
    +-lib
       +-dependency1.jar
       +-dependency2.jar
```
依赖的jar包在`BOOT-INF/lib`文件夹中。自己开发的类在`BOOT-INF/classes`文件夹中。

- 可执行的war包的目录结构
```java
example.war
 |
 +-META-INF
 |  +-MANIFEST.MF
 +-org
 |  +-springframework
 |     +-boot
 |        +-loader
 |           +-<spring boot loader classes>
 +-WEB-INF
    +-classes
    |  +-com
    |     +-mycompany
    |        +-project
    |           +-YourClasses.class
    +-lib
    |  +-dependency1.jar
    |  +-dependency2.jar
    +-lib-provided
       +-servlet-api.jar
       +-dependency3.jar
```
依赖包在`WEB-INF/lib`目录内，自己开发的类在`WEB-INF/classes`目录下。内嵌方式运行的tomcat运行方式需要但是传统容器的tomcat方式运行时不需要的类在`WEB-INF/lib-provided`目录下。

由上面的目录结构可见，打成可执行war包的目录结构与传统部署到tomcat容器中的目录基本无异。能正常运行运行就不足为奇了。

至于为什么使用Nested Jar的方式。可以参考[链接](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html)中的下面的一段话：

> Java does not provide any standard way to load nested jar files (that is, jar files that are themselves contained within a jar). This can be problematic if you need to distribute a self-contained application that can be run from the command line without unpacking.
> 
> To solve this problem, many developers use “shaded” jars. A shaded jar packages all classes, from all jars, into a single “uber jar”. The problem with shaded jars is that it becomes hard to see which libraries are actually in your application. It can also be problematic if the same filename is used (but with different content) in multiple jars. Spring Boot takes a different approach and lets you actually nest jars directly.

关于此次jar包的相关知识，可以参考下面的几个链接。

- [https://juejin.cn/post/6941618160386703390](https://juejin.cn/post/6941618160386703390)
- [https://mp.weixin.qq.com/s/lRmtLvTSjcGFFbBxzohFSQ](https://mp.weixin.qq.com/s/lRmtLvTSjcGFFbBxzohFSQ)
- [https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7](https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7)
- [https://blog.csdn.net/weixin_46768610/article/details/109377144](https://blog.csdn.net/weixin_46768610/article/details/109377144)

新版本的打包细节：

- [https://juejin.cn/post/6844904182743302151](https://juejin.cn/post/6844904182743302151)

那下面的主要问题就主要讨论jar包的范畴了。

## 第二个问题相关
第二个问题：tomcat[官方文档](https://tomcat.apache.org/tomcat-9.0-doc/config/context.html)中`JAR resources`部分有下面的一句话：
> During web application start, the JAR scanning process checks scanned JARs for content under /META-INF/resources. Where found, this static content is added to the JarResources.

意味着jar包中`META-INF/resources`目录中的资源文件也可以被扫描到。
所以通过配置jsp拷贝到这个目录中，在1.4.2及之前的版本可以正确运行jsp也是有依据的。
但是这个又引出来第一个问题，为什么1.4.2之后的版本不行，其中tomcat及其他的依赖包基本一致。这个就回到了第一个问题。

## 第三个问题相关
下面暂时先研究第三个问题：
把`org.apache.jasper`日志级别调整成`debug`模式。看一下jsp的查找路径是哪里。发现本地IDE运行的时候会找到`docbase目录`和项目`target目录`。从`target目录`中找到相应的jsp文件。所以本地运行正常。使用命令行`java -jar app.jar`的方式中只从`docbase`目录找，所以找不到。为什么找到了`target`目录，是因为`StaticResourceJars`类扫描的的时候将target目录当作资源目录添加到了tomcat的相关配置中。下面为判断的逻辑：target目录正好符合。
```
	private void addUrlFile(List<URL> urls, URL url, File file) {
		if ((file.isDirectory() && new File(file, "META-INF/resources").isDirectory())
				|| isResourcesJar(file)) {
			urls.add(url);
		}
	}
```

这个地方有两种不同启动方式的差异：
IDEA中`main`方法启动和命令行启动差异在于：
命令行启动的时候通过具体的`Launcher`的各种调用，设置`classloader`，准备加载的资源一类的操作，最终会调用`MainMethodRunner`，然后此方法会通过反射调用配置的`Start-Class`的值（springboot生成jar包的时候会在上面提到的`MANIFEST.MF`文件中的添加`Start-Class`属性。）。`TomcatEmbeddedWebappClassLoader`加载器为`LaunchedURLClassLoader` 

IDEA中启动的时候直接调用此类的`main`方法。`TomcatEmbeddedWebappClassLoader`加载器为`AppClassLoader`

启动细节可以查看下面的链接：

- [https://blog.csdn.net/weixin_46768610/article/details/109377144](https://blog.csdn.net/weixin_46768610/article/details/109377144)
- [https://mp.weixin.qq.com/s/jUZkpRADySBuyeIDMabPuw](https://mp.weixin.qq.com/s/jUZkpRADySBuyeIDMabPuw)
- [https://mp.weixin.qq.com/s/lRmtLvTSjcGFFbBxzohFSQ](https://mp.weixin.qq.com/s/lRmtLvTSjcGFFbBxzohFSQ)
- [https://juejin.cn/post/6844903890555502606](https://juejin.cn/post/6844903890555502606)
- [https://hengyun.tech/spring-boot-application-start-analysis/](https://hengyun.tech/spring-boot-application-start-analysis/)

## 第一个问题相关
剩下第一个问题：为什么1.4.2版本的可以
通过debug发现`org.springframework.boot.web.servlet.server.StaticResourceJars`代码中有对静态资源的处理的逻辑。其中在1.4.2会返回包含jar包的列表，但是2.x版本的返回的是空列表。由于没有读取到jar包的中静态资源，所以后面的404的发生也就可以说的同了。经查询两个不同版本的`spring-boot-loader`源码，发现1.4.2之后的版本中将`JarLauncher`类中的下面的一段逻辑给移除了，参看这个[commit](https://github.com/spring-projects/spring-boot/commit/2d8344d46d09c6c0de0bfe593f31b883a407f622)：

```
@Override
protected void postProcessClassPathArchives(List<Archive> archives) throws Exception {
	archives.add(0, getArchive());
}
```

关联的issues是这个[7595](https://github.com/spring-projects/spring-boot/issues/7595)：
说由于`JarLauncher` 将最终打出来的jar包添加到了`LaunchedURLClassLoader`中的classpath中。导致此包在`LaunchedURLClassLoader` 类和 其父类（system class loader）中的classpath中都有。会导致通过`LaunchedURLClassLoader`查找静态资源的时候会被重复找到。

从[8299](https://github.com/spring-projects/spring-boot/issues/8299)中可以看到下面的要点：
即使打成war包，`META-INF/resources`目录下的`/meta-inf-resources.txt`也是404的。

从[8324](https://github.com/spring-projects/spring-boot/issues/8324)中可以看到下面的[要点](https://github.com/spring-projects/spring-boot/issues/8324#issuecomment-280833828)：
Servlet 规范说从`WEB-INF/lib`目录内依赖的jar包中的加载`META-INF/resources`目录下的内容，而不是从主Achive中（即讲的springboot打出打jar包）读取`META-INF/resources`中的内容。1.4.2及早先的版本从主Achive中加载了`META-INF/resources`下的内容（实际是从`BOOT-INF/classes/META-INF/resources`读取）。1.4.3及之后的版本只从`BOOT-INF/lib`下jar包中的`META-INF/resources`来加载静态资源。

同时提出了当前情况的两个选择：

- 通过打成war包，使用`src/main/webapp`而非`src/main/resourcers/META-INF/resources/`作为静态资源的目录。使用`java -jar`方式启动。
- 将资源文件拆分到一个单独模块中，然后再应用中依赖此模块，这样的话就会以jar包的方式被打入`BOOT-INF/lib`目录。

部分相似关联的问题列表为：

- [https://github.com/spring-projects/spring-boot/issues/7449](https://github.com/spring-projects/spring-boot/issues/7449)
- [https://github.com/spring-projects/spring-boot/issues/7595](https://github.com/spring-projects/spring-boot/issues/7595)
- [https://github.com/spring-projects/spring-boot/issues/8299](https://github.com/spring-projects/spring-boot/issues/8299)
- [https://github.com/spring-projects/spring-boot/issues/8324](https://github.com/spring-projects/spring-boot/issues/8324)
- [https://github.com/spring-projects/spring-boot/issues/9014](https://github.com/spring-projects/spring-boot/issues/9014)
- [https://github.com/spring-projects/spring-boot/issues/6067](https://github.com/spring-projects/spring-boot/issues/6067)
- [https://github.com/spring-projects/spring-boot/issues/17240](https://github.com/spring-projects/spring-boot/issues/17240)
- [https://github.com/mybatis/spring-boot-starter/issues/108](https://github.com/mybatis/spring-boot-starter/issues/108)

## 解决方案
从上面的分析从可以得到下面的解决方案：

- 参照官方的建议使用war包方式并用`java -jar app.war`方式启动。
- 参照下面链接中的方案处理。通过自定义` TomcatContextCustomizer` 添加`JarResourceSet`的方式，可参考的源码在：`org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.StaticResourceConfigurer`的`lifecycleEvent`方法中。
   - [https://github.com/cdelgado83/jarservletcontext/blob/master/src/main/java/com/misc/Application.java](https://github.com/cdelgado83/jarservletcontext/blob/master/src/main/java/com/misc/Application.java)
   - [https://hengyun.tech/spring-boot-fat-jar-jsp-sample/](https://hengyun.tech/spring-boot-fat-jar-jsp-sample/)
   - [https://github.com/hengyunabc/spring-boot-fat-jar-jsp-sample](https://github.com/hengyunabc/spring-boot-fat-jar-jsp-sample)
- 参考webjar的方式，将jsp单独打成jar包。

**Comment by gongzhuoqun** [comment]
感谢，这是目前全网最全面的说明了。

我在补充一个方式，如果不打入jar包，外部挂载资源文件，
可以用 jar -Dloader.path 指定 /META-INF/resources/ 所属位置。

还有一种不知道是不是bug的现象，只要在启动jar的路径下，也就是user.dir 中包含static 这个目录，也可以被加载到
